[package]
name = "ckc-rs"
version = "0.1.2"
description = "Poker hand evaluation library"
authors = ["gaoler <gaoler@electronicpanopticon.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/ContractBridge/ckc-rs.git"
homepage = "https://github.com/ContractBridge/ckc-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.14", default-features = false }
bitvec = { version = "1.0.0", default-features = false, features = ["alloc", "atomic"] }

#libm = "0.2.1"
#serde = { version = "1.0.133", default-features = false, features = ["derive"] }

[dev-dependencies]
cardpack = "0.4.13"
