[package]
name = "ckc-rs"
version = "0.1.0"
authors = ["gaoler <gaoler@electronicpanopticon.com>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/ContractBridge/ckc-rs.git"
homepage = "https://github.com/ContractBridge/ckc-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4.14", default-features = false }
#libm = "0.2.1"
#serde = { version = "1.0.133", default-features = false, features = ["derive"] }
